version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres-interview-prep
    restart: always
    environment:
      POSTGRES_USER: interview-prep
      POSTGRES_PASSWORD: interview-prep
    ports:
      - 5432:5432

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: interview-prep
      MYSQL_USER: interview
      MYSQL_PASSWORD: interview
      MYSQL_ROOT_PASSWORD: interview
    ports:
      - 3306:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    depends_on: ['elasticsearch']
    ports:
      - 5601:5601

